version: '3'
services:
    rabbitmq:
        image: rabbitmq:management
        restart: on-failure
        expose:
          - "5672"
        ports:
          - 5672:5672
          - 15672:15672
        networks: 
          - cloud-native-network
    zipkin:
        image: openzipkin/zipkin
        restart: on-failure
        ports:
        - "9411:9411"
        expose:
        - "9411"
        networks: 
        - cloud-native-network
    config-server:
        build: ./spring-cloud-config-server
        expose:
        - 8888
        ports:
        - 8888:8888    
        networks:
        - cloud-native-network
    limits-service:
        build: ./limits-service
        expose:
        - 8666
        ports:
        - 8666:8666
        depends_on: 
        - rabbitmq
        - zipkin
        - config-server
        volumes: 
        - ./limits-service:/volume
        networks:
        - cloud-native-network
    eureka-naming-server:
        build: ./netflix-eureka-naming-server
        networks: 
        - cloud-native-network
        expose:
        - 8761
        ports:
        - 8761:8761
    netflix-zuul-api-gateway-server:
        build: ./netflix-zuul-api-gateway-server
        expose:
        - 8755
        ports:
        - 8755:8755
        volumes:
        - ./netflix-zuul-api-gateway-server:/volume         
        networks: 
        - cloud-native-network
        depends_on:
        - eureka-naming-server
        - zipkin
        - rabbitmq        
    currency-exchnage-service:
        build: ./currency_exchange_service
        expose:
        - 8000
        ports:
        - 8000:8000
        volumes:
        - ./currency_exchange_service:/volume         
        networks: 
        - cloud-native-network
        depends_on:
        - eureka-naming-server
        - netflix-zuul-api-gateway-server
        - zipkin
        - rabbitmq            
    currency-conversion-service:
        build: ./CurrencyConversionService
        expose:
        - 8100
        ports:
        - 8100
        volumes:
        - ./CurrencyConversionService:/volume         
        networks: 
        - cloud-native-network
        depends_on:
        - eureka-naming-server
        - netflix-zuul-api-gateway-server
        - currency-exchnage-service
        - zipkin
        - rabbitmq    
    currency-conversion-api:
        build: ./currency-conversion-api
        expose:
        - 5200
        ports:
        - 5200:5200
        volumes:
        - ./currency-conversion-client:/volume
        networks:
        - cloud-native-network
        depends_on: 
        - eureka-naming-server
        - netflix-zuul-api-gateway-server
        - currency-conversion-service
        - zipkin
        - rabbitmq    
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - cloud-native-volume:/var/lib/mysql
        networks:
        - cloud-native-network
volumes:
    cloud-native-volume:
networks:
    cloud-native-network: {}
              