version: '3'
services:
    spring-cloud-api-gateway-server:
        container_name: api-gateway
        build:
            context: spring-cloud-api-gateway-server
            dockerfile: Dockerfile.tnl
        expose:
            - 8755
        ports:
            - 8755:8755
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
    currency-exchnage-service:
        container_name: c-exchnage-service
        build:
            context: currency-exchange-service
            dockerfile: Dockerfile.tnl
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    currency-conversion-service:
        container_name: c-conversion-service
        build:
            context: currency-conversion-service
            dockerfile: Dockerfile.tnl
        expose:
            - 8100
        ports:
            - 8100:8100
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    country-service:
        container_name: country-service
        build:
            context: country-service
            dockerfile: Dockerfile.tnl
        expose:
            - 8300
        ports:
            - 8300:8300
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    api-composer:
        container_name: api-composer
        build:
            context: api-composer
            dockerfile: Dockerfile.tnl
        expose:
            - 5200
        ports:
            - 5200:5200
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    user-service:
        container_name: user-service
        build:
            context: user-service
            dockerfile: Dockerfile.tnl
        expose:
            - 8900
        ports:
            - 8900:8900
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    audit-service:
        container_name: audit-service
        build:
            context: audit-service
            dockerfile: Dockerfile.tnl
        expose:
            - 8950
        ports:
            - 8950:8950
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    react-client:
        container_name: react-client
        build:
            context: ./clients/3cn-react-client/
        depends_on:
            - api-composer
        ports:
            - '3000:80'
        networks:
            - envcn_cloud-native-network
volumes:
    cloud-native-volume:
networks:
    envcn_cloud-native-network:
        external: true